title: eilamg.dev
url: https://eilamg.dev

author: Eilam Gilboa
email: mail@eilamg.dev

theme: minima

exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - CNAME
    - .local/
